PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        p:P22 [ ps:P22 wd:Q75794772 ] ;
        p:P25 [ ps:P25 ?y1 ] ;
        p:P21 [ ps:P21 ?y2a ]
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        p:P22 [ ps:P22 wd:Q75794772 ] ;
        p:P25 [ ps:P25 ?y1 ] ;
        p:P21 [ ps:P21 ?y2b ]
    }
  }
}
