PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        p:P921 [ ps:P921 wd:Q115 ] ;
        p:P2860 [ ps:P2860 ?y1 ] ;
        p:P50 [ ps:P50 ?y2a ]
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        p:P921 [ ps:P921 wd:Q115 ] ;
        p:P2860 [ ps:P2860 ?y1 ] ;
        p:P50 [ ps:P50 ?y2b ]
    }
  }
}
