PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      p:P19 [ ps:P19 wd:Q13298 ] ;
      p:P27 [ ps:P27 wd:Q40 ] ;
      p:P1412 [ ps:P1412 ?y1 ] ;
      p:P106 [ ps:P106 ?y2 ] ;
      p:P21 [ ps:P21 ?y3a ] ;
      p:P735 [ ps:P735 ?y4a ]
  }
  MINUS
  {
    ?x
      p:P19 [ ps:P19 wd:Q13298 ] ;
      p:P27 [ ps:P27 wd:Q40 ] ;
      p:P1412 [ ps:P1412 ?y1 ] ;
      p:P106 [ ps:P106 ?y2 ] ;
      p:P21 [ ps:P21 ?y3b ] ;
      p:P735 [ ps:P735 ?y4b ]
  }
}
