PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        p:P361 [ ps:P361 wd:Q24783797 ] ;
        p:P681 [ ps:P681 wd:Q79899 ] ;
        p:P682 [ ps:P682 ?y1 ] ;
        p:P702 [ ps:P702 ?y2 ] ;
        p:P527 [ ps:P527 ?y3a ] ;
        p:P703 [ ps:P703 ?y4a ]
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        p:P361 [ ps:P361 wd:Q24783797 ] ;
        p:P681 [ ps:P681 wd:Q79899 ] ;
        p:P682 [ ps:P682 ?y1 ] ;
        p:P702 [ ps:P702 ?y2 ] ;
        p:P527 [ ps:P527 ?y3b ] ;
        p:P703 [ ps:P703 ?y4b ]
    }
  }
}
