PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT
  ?x ?y1
  ?p_Add
  ?p_Add_summand_1_Sum
  ?p_Add_summand_1_Sum_summand_Product
  ?p_Add_summand_1_Sum
  ?p_Add_summand_1_Sum_summand_Product
  ?p_Add_summand_1_Sum_summand_Product_factor_1_Sum
  ?p_Add_summand_1_Sum_summand_Product_factor_1_Sum_summand_Statement
  ?p_Add_summand_1_Sum_summand_Product_factor_2_Sum
  ?p_Add_summand_1_Sum_summand_Product_factor_2_Sum_summand_Statement
  ?p_Add_summand_1_Sum_summand_Product_factor_3_Sum
  ?p_Add_summand_1_Sum_summand_Product_factor_3_Sum_summand_Statement
  ?p_Add_summand_2_Sum_summand_Product_factor_1_Sum
  ?p_Add_summand_2_Sum_summand_Product_factor_1_Sum_summand_Statement
  ?p_Add_summand_2_Sum_summand_Product_factor_2_Sum
  ?p_Add_summand_2_Sum_summand_Product_factor_2_Sum_summand_Statement
  ?p_Add_summand_2_Sum_summand_Product_factor_3_Sum
  ?p_Add_summand_2_Sum_summand_Product_factor_3_Sum_summand_Statement
WHERE {
  {
    {
      SELECT
        ?x ?y1
        ?p_Add_summand_1_Sum
        ?p_Add_summand_1_Sum_summand_Product
        ?p_Add_summand_1_Sum_summand_Product_factor_1_Sum
        ?p_Add_summand_1_Sum_summand_Product_factor_1_Sum_summand_Statement
        ?p_Add_summand_1_Sum_summand_Product_factor_2_Sum
        ?p_Add_summand_1_Sum_summand_Product_factor_2_Sum_summand_Statement
        ?p_Add_summand_1_Sum_summand_Product_factor_3_Sum
        ?p_Add_summand_1_Sum_summand_Product_factor_3_Sum_summand_Statement
      WHERE {
        {
          ?x p:P27 ?p_Add_summand_1_Sum_summand_Product_factor_1_Sum_summand_Statement .
          ?p_Add_summand_1_Sum_summand_Product_factor_1_Sum_summand_Statement ps:P27 wd:Q9903 .
          ?x p:P734 ?p_Add_summand_1_Sum_summand_Product_factor_2_Sum_summand_Statement .
          ?p_Add_summand_1_Sum_summand_Product_factor_2_Sum_summand_Statement ps:P734 ?y1 .
          ?x p:P21 ?p_Add_summand_1_Sum_summand_Product_factor_3_Sum_summand_Statement .
          ?p_Add_summand_1_Sum_summand_Product_factor_3_Sum_summand_Statement ps:P21 ?y2a
        }
        BIND (URI(concat(
          "http://example.org/p_Add_summand_1_Sum_summand_Product_factor_1_Sum/",
          "?x=",ENCODE_FOR_URI(?x)
        )) AS ?p_Add_summand_1_Sum_summand_Product_factor_1_Sum)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_1_Sum_summand_Product_factor_2_Sum/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y1=",ENCODE_FOR_URI(?y1)
        )) AS ?p_Add_summand_1_Sum_summand_Product_factor_2_Sum)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_1_Sum_summand_Product_factor_3_Sum/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y2a=",ENCODE_FOR_URI(?y2a)
        )) AS ?p_Add_summand_1_Sum_summand_Product_factor_3_Sum)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_1_Sum_summand_Product/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y1=",ENCODE_FOR_URI(?y1),
          "&y2a=",ENCODE_FOR_URI(?y2a)
        )) AS ?p_Add_summand_1_Sum_summand_Product)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_1_Sum/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y1=",ENCODE_FOR_URI(?y1)
        )) AS ?p_Add_summand_1_Sum)
      }
    }
    UNION
    {
      SELECT
        ?x ?y1
        ?p_Add_summand_2_Sum
        ?p_Add_summand_2_Sum_summand_Product
        ?p_Add_summand_2_Sum_summand_Product_factor_1_Sum
        ?p_Add_summand_2_Sum_summand_Product_factor_1_Sum_summand_Statement
        ?p_Add_summand_2_Sum_summand_Product_factor_2_Sum
        ?p_Add_summand_2_Sum_summand_Product_factor_2_Sum_summand_Statement
        ?p_Add_summand_2_Sum_summand_Product_factor_3_Sum
        ?p_Add_summand_2_Sum_summand_Product_factor_3_Sum_summand_Statement
      WHERE {
        {
          ?x p:P27 ?p_Add_summand_2_Sum_summand_Product_factor_1_Sum_summand_Statement .
          ?p_Add_summand_2_Sum_summand_Product_factor_1_Sum_summand_Statement ps:P27 wd:Q9903 .
          ?x p:P734 ?p_Add_summand_2_Sum_summand_Product_factor_2_Sum_summand_Statement .
          ?p_Add_summand_2_Sum_summand_Product_factor_2_Sum_summand_Statement ps:P734 ?y1 .
          ?x p:P21 ?p_Add_summand_2_Sum_summand_Product_factor_3_Sum_summand_Statement .
          ?p_Add_summand_2_Sum_summand_Product_factor_3_Sum_summand_Statement ps:P21 ?y2b
        }
        BIND (URI(concat(
          "http://example.org/p_Add_summand_2_Sum_summand_Product_factor_1_Sum/",
          "?x=",ENCODE_FOR_URI(?x)
        )) AS ?p_Add_summand_2_Sum_summand_Product_factor_1_Sum)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_2_Sum_summand_Product_factor_2_Sum/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y1=",ENCODE_FOR_URI(?y1)
        )) AS ?p_Add_summand_2_Sum_summand_Product_factor_2_Sum)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_2_Sum_summand_Product_factor_3_Sum/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y2b=",ENCODE_FOR_URI(?y2b)
        )) AS ?p_Add_summand_2_Sum_summand_Product_factor_3_Sum)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_2_Sum_summand_Product/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y1=",ENCODE_FOR_URI(?y1),
          "&y2b=",ENCODE_FOR_URI(?y2b)
        )) AS ?p_Add_summand_2_Sum_summand_Product)
        BIND (URI(concat(
          "http://example.org/p_Add_summand_2_Sum/",
          "?x=",ENCODE_FOR_URI(?x),
          "&y1=",ENCODE_FOR_URI(?y1)
        )) AS ?p_Add_summand_2_Sum)
      }
    }
  }
  BIND (URI(concat(
    "http://example.org/p_Add/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1)
  )) AS ?p_Add)
}
