PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P361 wd:Q41797240 ;
    wdt:P279 wd:Q8054 ;
    wdt:P680 ?y1 ;
    wdt:P681 ?y2 ;
    wdt:P682 ?y3 ;
    wdt:P702 ?y4
}
