PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P1412 wd:Q188 ;
    wdt:P463 wd:Q44687 ;
    wdt:P27 ?y1 ;
    wdt:P21 ?y2 ;
    wdt:P607 ?y3 ;
    wdt:P937 ?y4
}
