PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P58 wd:Q4714925 ;
    wdt:P86 wd:Q319777 ;
    wdt:P2515 ?y1 ;
    wdt:P57 ?y2 ;
    wdt:P161 ?y3 ;
    wdt:P495 ?y4
}
