PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P1346 wd:Q59711999 ;
    wdt:P2094 wd:Q58954843 ;
    wdt:P641 ?y1 ;
    wdt:P2283 ?y2 ;
    wdt:P664 ?y3 ;
    wdt:P710 ?y4
}
