PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P108 wd:Q1235594 ;
    wdt:P19 wd:Q15090 ;
    wdt:P1412 ?y1 ;
    wdt:P69 ?y2 ;
    wdt:P106 ?y3 ;
    wdt:P735 ?y4
}
