PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P682 wd:Q21103056 ;
    wdt:P681 wd:Q12821248 ;
    wdt:P703 ?y1 ;
    wdt:P361 ?y2 ;
    wdt:P680 ?y3 ;
    wdt:P702 ?y4
}
