PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P703 wd:Q21102993 ;
    wdt:P279 wd:Q8054 ;
    wdt:P527 ?y1 ;
    wdt:P680 ?y2 ;
    wdt:P702 ?y3 ;
    wdt:P361 ?y4
}
