PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P140 wd:Q1841 ;
    wdt:P138 wd:Q442516 ;
    wdt:P17 ?y1 ;
    wdt:P84 ?y2 ;
    wdt:P131 ?y3 ;
    wdt:P1435 ?y4
}
