PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P27 wd:Q142 ;
    wdt:P734 wd:Q65099326 ;
    wdt:P106 ?y1 ;
    wdt:P39 ?y2 ;
    wdt:P21 ?y3 ;
    wdt:P735 ?y4
}
