PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1
WHERE {
  ?x
    p:P527 [ ps:P527 wd:Q24772108 ] ;
    p:P279 [ ps:P279 ?y1 ] ;
    p:P682 [ ps:P682 ?y2 ]
}
