PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1
WHERE {
  ?x
    p:P21 [ ps:P21 wd:Q6581097 ] ;
    p:P734 [ ps:P734 ?y1 ] ;
    p:P19 [ ps:P19 ?y2 ]
}
