PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P5607 wd:Q11693447 ;
        wdt:P17 ?y1 ;
        wdt:P708 ?y2a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P5607 wd:Q11693447 ;
        wdt:P17 ?y1 ;
        wdt:P708 ?y2b
    }
  }
}
