PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P131 wd:Q393476 ;
        wdt:P138 ?y1 ;
        wdt:P17 ?y2a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P131 wd:Q393476 ;
        wdt:P138 ?y1 ;
        wdt:P17 ?y2b
    }
  }
}
