PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P937 wd:Q60 ;
        wdt:P106 ?y1 ;
        wdt:P21 ?y2a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P937 wd:Q60 ;
        wdt:P106 ?y1 ;
        wdt:P21 ?y2b
    }
  }
}
