PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P106 wd:Q42973 ;
        wdt:P735 ?y1 ;
        wdt:P108 ?y2a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P106 wd:Q42973 ;
        wdt:P735 ?y1 ;
        wdt:P108 ?y2b
    }
  }
}
