PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P921 wd:Q115 ;
        wdt:P2860 ?y1 ;
        wdt:P50 ?y2a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P921 wd:Q115 ;
        wdt:P2860 ?y1 ;
        wdt:P50 ?y2b
    }
  }
}
