PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P551 wd:Q268873 ;
      wdt:P106 wd:Q6625963 ;
      wdt:P735 ?y1 ;
      wdt:P734 ?y2 ;
      wdt:P27 ?y3a ;
      wdt:P361 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P551 wd:Q268873 ;
      wdt:P106 wd:Q6625963 ;
      wdt:P735 ?y1 ;
      wdt:P734 ?y2 ;
      wdt:P27 ?y3b ;
      wdt:P361 ?y4b
  }
}
