PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P735 wd:Q1778168 ;
      wdt:P19 wd:Q202177 ;
      wdt:P463 ?y1 ;
      wdt:P106 ?y2 ;
      wdt:P734 ?y3a ;
      wdt:P1196 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P735 wd:Q1778168 ;
      wdt:P19 wd:Q202177 ;
      wdt:P463 ?y1 ;
      wdt:P106 ?y2 ;
      wdt:P734 ?y3b ;
      wdt:P1196 ?y4b
  }
}
