PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P69 wd:Q6765664 ;
      wdt:P1050 wd:Q131755 ;
      wdt:P19 ?y1 ;
      wdt:P735 ?y2 ;
      wdt:P734 ?y3a ;
      wdt:P21 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P69 wd:Q6765664 ;
      wdt:P1050 wd:Q131755 ;
      wdt:P19 ?y1 ;
      wdt:P735 ?y2 ;
      wdt:P734 ?y3b ;
      wdt:P21 ?y4b
  }
}
