PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P20 wd:Q72 ;
      wdt:P108 wd:Q677683 ;
      wdt:P735 ?y1 ;
      wdt:P19 ?y2 ;
      wdt:P21 ?y3a ;
      wdt:P106 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P20 wd:Q72 ;
      wdt:P108 wd:Q677683 ;
      wdt:P735 ?y1 ;
      wdt:P19 ?y2 ;
      wdt:P21 ?y3b ;
      wdt:P106 ?y4b
  }
}
