PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P106 wd:Q82955 ;
      wdt:P735 wd:Q2829505 ;
      wdt:P734 ?y1 ;
      wdt:P21 ?y2 ;
      wdt:P39 ?y3a ;
      wdt:P27 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P106 wd:Q82955 ;
      wdt:P735 wd:Q2829505 ;
      wdt:P734 ?y1 ;
      wdt:P21 ?y2 ;
      wdt:P39 ?y3b ;
      wdt:P27 ?y4b
  }
}
