PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P19 wd:Q13298 ;
      wdt:P27 wd:Q40 ;
      wdt:P1412 ?y1 ;
      wdt:P106 ?y2 ;
      wdt:P21 ?y3a ;
      wdt:P735 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P19 wd:Q13298 ;
      wdt:P27 wd:Q40 ;
      wdt:P1412 ?y1 ;
      wdt:P106 ?y2 ;
      wdt:P21 ?y3b ;
      wdt:P735 ?y4b
  }
}
