PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P703 wd:Q15978631 ;
      wdt:P684 wd:Q18254171 ;
      wdt:P688 ?y1 ;
      wdt:P2548 ?y2 ;
      wdt:P279 ?y3a ;
      wdt:P2293 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P703 wd:Q15978631 ;
      wdt:P684 wd:Q18254171 ;
      wdt:P688 ?y1 ;
      wdt:P2548 ?y2 ;
      wdt:P279 ?y3b ;
      wdt:P2293 ?y4b
  }
}
