PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P106 wd:Q16145150 ;
      wdt:P1303 wd:Q17172850 ;
      wdt:P21 ?y1 ;
      wdt:P27 ?y2 ;
      wdt:P735 ?y3a ;
      wdt:P734 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P106 wd:Q16145150 ;
      wdt:P1303 wd:Q17172850 ;
      wdt:P21 ?y1 ;
      wdt:P27 ?y2 ;
      wdt:P735 ?y3b ;
      wdt:P734 ?y4b
  }
}
