PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  {
    ?x
      wdt:P19 wd:Q847130 ;
      wdt:P641 wd:Q2736 ;
      wdt:P21 ?y1 ;
      wdt:P413 ?y2 ;
      wdt:P54 ?y3a ;
      wdt:P27 ?y4a
  }
  MINUS
  {
    ?x
      wdt:P19 wd:Q847130 ;
      wdt:P641 wd:Q2736 ;
      wdt:P21 ?y1 ;
      wdt:P413 ?y2 ;
      wdt:P54 ?y3b ;
      wdt:P27 ?y4b
  }
}
