PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P166 wd:Q1139785 ;
        wdt:P1412 wd:Q7026 ;
        wdt:P21 ?y1 ;
        wdt:P735 ?y2 ;
        wdt:P800 ?y3a ;
        wdt:P106 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P166 wd:Q1139785 ;
        wdt:P1412 wd:Q7026 ;
        wdt:P21 ?y1 ;
        wdt:P735 ?y2 ;
        wdt:P800 ?y3b ;
        wdt:P106 ?y4b
    }
  }
}
