PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P680 wd:Q21111783 ;
        wdt:P702 wd:Q22262904 ;
        wdt:P279 ?y1 ;
        wdt:P527 ?y2 ;
        wdt:P682 ?y3a ;
        wdt:P703 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P680 wd:Q21111783 ;
        wdt:P702 wd:Q22262904 ;
        wdt:P279 ?y1 ;
        wdt:P527 ?y2 ;
        wdt:P682 ?y3b ;
        wdt:P703 ?y4b
    }
  }
}
