PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P1303 wd:Q5994 ;
        wdt:P735 wd:Q168280 ;
        wdt:P27 ?y1 ;
        wdt:P106 ?y2 ;
        wdt:P21 ?y3a ;
        wdt:P69 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P1303 wd:Q5994 ;
        wdt:P735 wd:Q168280 ;
        wdt:P27 ?y1 ;
        wdt:P106 ?y2 ;
        wdt:P21 ?y3b ;
        wdt:P69 ?y4b
    }
  }
}
