PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P106 wd:Q250867 ;
        wdt:P1598 wd:Q555975 ;
        wdt:P39 ?y1 ;
        wdt:P734 ?y2 ;
        wdt:P19 ?y3a ;
        wdt:P1950 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P106 wd:Q250867 ;
        wdt:P1598 wd:Q555975 ;
        wdt:P39 ?y1 ;
        wdt:P734 ?y2 ;
        wdt:P19 ?y3b ;
        wdt:P1950 ?y4b
    }
  }
}
