PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P54 wd:Q650840 ;
        wdt:P641 wd:Q5369 ;
        wdt:P27 ?y1 ;
        wdt:P413 ?y2 ;
        wdt:P19 ?y3a ;
        wdt:P106 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P54 wd:Q650840 ;
        wdt:P641 wd:Q5369 ;
        wdt:P27 ?y1 ;
        wdt:P413 ?y2 ;
        wdt:P19 ?y3b ;
        wdt:P106 ?y4b
    }
  }
}
