PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P21 wd:Q6581072 ;
        wdt:P1412 wd:Q150 ;
        wdt:P108 ?y1 ;
        wdt:P27 ?y2 ;
        wdt:P735 ?y3a ;
        wdt:P106 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P21 wd:Q6581072 ;
        wdt:P1412 wd:Q150 ;
        wdt:P108 ?y1 ;
        wdt:P27 ?y2 ;
        wdt:P735 ?y3b ;
        wdt:P106 ?y4b
    }
  }
}
