PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P703 wd:Q21102993 ;
        wdt:P279 wd:Q8054 ;
        wdt:P527 ?y1 ;
        wdt:P680 ?y2 ;
        wdt:P702 ?y3a ;
        wdt:P361 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P703 wd:Q21102993 ;
        wdt:P279 wd:Q8054 ;
        wdt:P527 ?y1 ;
        wdt:P680 ?y2 ;
        wdt:P702 ?y3b ;
        wdt:P361 ?y4b
    }
  }
}
