PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P682 wd:Q847556 ;
        wdt:P527 wd:Q24774001 ;
        wdt:P703 ?y1 ;
        wdt:P279 ?y2 ;
        wdt:P680 ?y3a ;
        wdt:P361 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P682 wd:Q847556 ;
        wdt:P527 wd:Q24774001 ;
        wdt:P703 ?y1 ;
        wdt:P279 ?y2 ;
        wdt:P680 ?y3b ;
        wdt:P361 ?y4b
    }
  }
}
