PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P19 wd:Q582081 ;
        wdt:P1412 wd:Q188 ;
        wdt:P108 ?y1 ;
        wdt:P27 ?y2 ;
        wdt:P106 ?y3a ;
        wdt:P166 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P19 wd:Q582081 ;
        wdt:P1412 wd:Q188 ;
        wdt:P108 ?y1 ;
        wdt:P27 ?y2 ;
        wdt:P106 ?y3b ;
        wdt:P166 ?y4b
    }
  }
}
