PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P703 wd:Q184224 ;
        wdt:P688 wd:Q28560067 ;
        wdt:P684 ?y1 ;
        wdt:P279 ?y2 ;
        wdt:P1057 ?y3a ;
        wdt:P2548 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P703 wd:Q184224 ;
        wdt:P688 wd:Q28560067 ;
        wdt:P684 ?y1 ;
        wdt:P279 ?y2 ;
        wdt:P1057 ?y3b ;
        wdt:P2548 ?y4b
    }
  }
}
