PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P703 wd:Q21398749 ;
        wdt:P527 wd:Q24725862 ;
        wdt:P702 ?y1 ;
        wdt:P682 ?y2 ;
        wdt:P680 ?y3a ;
        wdt:P279 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P703 wd:Q21398749 ;
        wdt:P527 wd:Q24725862 ;
        wdt:P702 ?y1 ;
        wdt:P682 ?y2 ;
        wdt:P680 ?y3b ;
        wdt:P279 ?y4b
    }
  }
}
