PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT *
WHERE {
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P20 wd:Q198140 ;
        wdt:P166 wd:Q4375578 ;
        wdt:P735 ?y1 ;
        wdt:P21 ?y2 ;
        wdt:P607 ?y3a ;
        wdt:P119 ?y4a
    }
  }
  UNION
  {
    SELECT ?x ?y1
    WHERE {
      ?x
        wdt:P20 wd:Q198140 ;
        wdt:P166 wd:Q4375578 ;
        wdt:P735 ?y1 ;
        wdt:P21 ?y2 ;
        wdt:P607 ?y3b ;
        wdt:P119 ?y4b
    }
  }
}
