PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      p:P19 [ ps:P19 wd:Q1492 ] ;
      p:P106 [ ps:P106 ?y1 ] ;
      p:P735 [ ps:P735 ?y2a ]
  }
  MINUS
  {
    ?x
      p:P19 [ ps:P19 wd:Q1492 ] ;
      p:P106 [ ps:P106 ?y1 ] ;
      p:P735 [ ps:P735 ?y2b ]
  }
}
