PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      p:P170 [ ps:P170 wd:Q7780 ] ;
      p:P276 [ ps:P276 ?y1 ] ;
      p:P195 [ ps:P195 ?y2a ]
  }
  MINUS
  {
    ?x
      p:P170 [ ps:P170 wd:Q7780 ] ;
      p:P276 [ ps:P276 ?y1 ] ;
      p:P195 [ ps:P195 ?y2b ]
  }
}
