PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT
  ?x ?y1
  ?p_Sum
  ?p_Sum_summand_Product
  ?p_Sum_summand_Product_factor_1_Sum
  ?p_Sum_summand_Product_factor_1_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_2_Sum
  ?p_Sum_summand_Product_factor_2_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_3_Sum
  ?p_Sum_summand_Product_factor_3_Sum_summand_Statement
WHERE {
  {
    ?x p:P6886 ?p_Sum_summand_Product_factor_1_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_1_Sum_summand_Statement ps:P6886 wd:Q143 .
    ?x p:P21 ?p_Sum_summand_Product_factor_2_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_2_Sum_summand_Statement ps:P21 ?y1 .
    ?x p:P27 ?p_Sum_summand_Product_factor_3_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_3_Sum_summand_Statement ps:P27 ?y2
  }
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_1_Sum/",
    "?x=",ENCODE_FOR_URI(?x)
  )) AS ?p_Sum_summand_Product_factor_1_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_2_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1)
  )) AS ?p_Sum_summand_Product_factor_2_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_3_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y2=",ENCODE_FOR_URI(?y2)
  )) AS ?p_Sum_summand_Product_factor_3_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1),
    "&y2=",ENCODE_FOR_URI(?y2)
  )) AS ?p_Sum_summand_Product)
  BIND (URI(concat(
    "http://example.org/p_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1)
  )) AS ?p_Sum)
}
