PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT
  ?x ?y1 ?y2
  ?p_Sum
  ?p_Sum_summand_Product
  ?p_Sum_summand_Product_factor_1_Sum
  ?p_Sum_summand_Product_factor_1_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_2_Sum
  ?p_Sum_summand_Product_factor_2_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_3_Sum
  ?p_Sum_summand_Product_factor_3_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_4_Sum
  ?p_Sum_summand_Product_factor_4_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_5_Sum
  ?p_Sum_summand_Product_factor_5_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_6_Sum
  ?p_Sum_summand_Product_factor_6_Sum_summand_Statement
WHERE {
  {
    ?x p:P488 ?p_Sum_summand_Product_factor_1_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_1_Sum_summand_Statement ps:P488 wd:Q59564897 .
    ?x p:P17 ?p_Sum_summand_Product_factor_2_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_2_Sum_summand_Statement ps:P17 wd:Q142 .
    ?x p:P131 ?p_Sum_summand_Product_factor_3_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_3_Sum_summand_Statement ps:P131 ?y1 .
    ?x p:P167 ?p_Sum_summand_Product_factor_4_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_4_Sum_summand_Statement ps:P167 ?y2 .
    ?x p:P355 ?p_Sum_summand_Product_factor_5_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_5_Sum_summand_Statement ps:P355 ?y3 .
    ?x p:P1454 ?p_Sum_summand_Product_factor_6_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_6_Sum_summand_Statement ps:P1454 ?y4
  }
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_1_Sum/",
    "?x=",ENCODE_FOR_URI(?x)
  )) AS ?p_Sum_summand_Product_factor_1_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_2_Sum/",
    "?x=",ENCODE_FOR_URI(?x)
  )) AS ?p_Sum_summand_Product_factor_2_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_3_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1)
  )) AS ?p_Sum_summand_Product_factor_3_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_4_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y2=",ENCODE_FOR_URI(?y2)
  )) AS ?p_Sum_summand_Product_factor_4_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_5_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y3=",ENCODE_FOR_URI(?y3)
  )) AS ?p_Sum_summand_Product_factor_5_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_6_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y4=",ENCODE_FOR_URI(?y4)
  )) AS ?p_Sum_summand_Product_factor_6_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1),
    "&y2=",ENCODE_FOR_URI(?y2),
    "&y3=",ENCODE_FOR_URI(?y3),
    "&y4=",ENCODE_FOR_URI(?y4)
  )) AS ?p_Sum_summand_Product)
  BIND (URI(concat(
    "http://example.org/p_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1),
    "&y2=",ENCODE_FOR_URI(?y2)
  )) AS ?p_Sum)
}
