PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT
  ?x ?y1 ?y2
  ?p_Sum
  ?p_Sum_summand_Product
  ?p_Sum_summand_Product_factor_1_Sum
  ?p_Sum_summand_Product_factor_1_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_2_Sum
  ?p_Sum_summand_Product_factor_2_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_3_Sum
  ?p_Sum_summand_Product_factor_3_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_4_Sum
  ?p_Sum_summand_Product_factor_4_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_5_Sum
  ?p_Sum_summand_Product_factor_5_Sum_summand_Statement
  ?p_Sum_summand_Product_factor_6_Sum
  ?p_Sum_summand_Product_factor_6_Sum_summand_Statement
WHERE {
  {
    ?x p:P197 ?p_Sum_summand_Product_factor_1_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_1_Sum_summand_Statement ps:P197 wd:Q72594679 .
    ?x p:P137 ?p_Sum_summand_Product_factor_2_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_2_Sum_summand_Statement ps:P137 wd:Q879270 .
    ?x p:P81 ?p_Sum_summand_Product_factor_3_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_3_Sum_summand_Statement ps:P81 ?y1 .
    ?x p:P17 ?p_Sum_summand_Product_factor_4_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_4_Sum_summand_Statement ps:P17 ?y2 .
    ?x p:P127 ?p_Sum_summand_Product_factor_5_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_5_Sum_summand_Statement ps:P127 ?y3 .
    ?x p:P131 ?p_Sum_summand_Product_factor_6_Sum_summand_Statement .
    ?p_Sum_summand_Product_factor_6_Sum_summand_Statement ps:P131 ?y4
  }
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_1_Sum/",
    "?x=",ENCODE_FOR_URI(?x)
  )) AS ?p_Sum_summand_Product_factor_1_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_2_Sum/",
    "?x=",ENCODE_FOR_URI(?x)
  )) AS ?p_Sum_summand_Product_factor_2_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_3_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1)
  )) AS ?p_Sum_summand_Product_factor_3_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_4_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y2=",ENCODE_FOR_URI(?y2)
  )) AS ?p_Sum_summand_Product_factor_4_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_5_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y3=",ENCODE_FOR_URI(?y3)
  )) AS ?p_Sum_summand_Product_factor_5_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product_factor_6_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y4=",ENCODE_FOR_URI(?y4)
  )) AS ?p_Sum_summand_Product_factor_6_Sum)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1),
    "&y2=",ENCODE_FOR_URI(?y2),
    "&y3=",ENCODE_FOR_URI(?y3),
    "&y4=",ENCODE_FOR_URI(?y4)
  )) AS ?p_Sum_summand_Product)
  BIND (URI(concat(
    "http://example.org/p_Sum/",
    "?x=",ENCODE_FOR_URI(?x),
    "&y1=",ENCODE_FOR_URI(?y1),
    "&y2=",ENCODE_FOR_URI(?y2)
  )) AS ?p_Sum)
}
