PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      wdt:P1433 wd:Q1659906 ;
      wdt:P50 ?y1 ;
      wdt:P921 ?y2a
  }
  MINUS
  {
    ?x
      wdt:P1433 wd:Q1659906 ;
      wdt:P50 ?y1 ;
      wdt:P921 ?y2b
  }
}
