PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      wdt:P407 wd:Q1860 ;
      wdt:P1433 ?y1 ;
      wdt:P50 ?y2a
  }
  MINUS
  {
    ?x
      wdt:P407 wd:Q1860 ;
      wdt:P1433 ?y1 ;
      wdt:P50 ?y2b
  }
}
