PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      wdt:P50 wd:Q47399445 ;
      wdt:P407 ?y1 ;
      wdt:P1433 ?y2a
  }
  MINUS
  {
    ?x
      wdt:P50 wd:Q47399445 ;
      wdt:P407 ?y1 ;
      wdt:P1433 ?y2b
  }
}
