PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      wdt:P17 wd:Q668 ;
      wdt:P131 ?y1 ;
      wdt:P421 ?y2a
  }
  MINUS
  {
    ?x
      wdt:P17 wd:Q668 ;
      wdt:P131 ?y1 ;
      wdt:P421 ?y2b
  }
}
