PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      wdt:P141 wd:Q278113 ;
      wdt:P105 ?y1 ;
      wdt:P171 ?y2a
  }
  MINUS
  {
    ?x
      wdt:P141 wd:Q278113 ;
      wdt:P105 ?y1 ;
      wdt:P171 ?y2b
  }
}
