PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      wdt:P276 wd:Q1201549 ;
      wdt:P180 ?y1 ;
      wdt:P195 ?y2a
  }
  MINUS
  {
    ?x
      wdt:P276 wd:Q1201549 ;
      wdt:P180 ?y1 ;
      wdt:P195 ?y2b
  }
}
