PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1
WHERE {
  {
    ?x
      wdt:P186 wd:Q34095 ;
      wdt:P195 ?y1 ;
      wdt:P276 ?y2a
  }
  MINUS
  {
    ?x
      wdt:P186 wd:Q34095 ;
      wdt:P195 ?y1 ;
      wdt:P276 ?y2b
  }
}
