PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P27 wd:Q30 ;
    wdt:P735 wd:Q59204194 ;
    wdt:P106 ?y1 ;
    wdt:P1303 ?y2 ;
    wdt:P136 ?y3 ;
    wdt:P412 ?y4
}
