PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P921 wd:Q689846 ;
    wdt:P272 wd:Q21036757 ;
    wdt:P136 ?y1 ;
    wdt:P57 ?y2 ;
    wdt:P449 ?y3 ;
    wdt:P364 ?y4
}
