PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P2505 wd:Q6770747 ;
    wdt:P138 wd:Q6770747 ;
    wdt:P2674 ?y1 ;
    wdt:P131 ?y2 ;
    wdt:P2673 ?y3 ;
    wdt:P177 ?y4
}
