PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    wdt:P106 wd:Q13382576 ;
    wdt:P19 wd:Q2868 ;
    wdt:P1344 ?y1 ;
    wdt:P27 ?y2 ;
    wdt:P21 ?y3 ;
    wdt:P641 ?y4
}
