PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P39 [ ps:P39 wd:Q18015642 ] ;
    p:P40 [ ps:P40 wd:Q76208244 ] ;
    p:P1412 [ ps:P1412 ?y1 ] ;
    p:P735 [ ps:P735 ?y2 ] ;
    p:P106 [ ps:P106 ?y3 ] ;
    p:P69 [ ps:P69 ?y4 ]
}
