PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P735 [ ps:P735 wd:Q1778168 ] ;
    p:P19 [ ps:P19 wd:Q202177 ] ;
    p:P463 [ ps:P463 ?y1 ] ;
    p:P106 [ ps:P106 ?y2 ] ;
    p:P734 [ ps:P734 ?y3 ] ;
    p:P1196 [ ps:P1196 ?y4 ]
}
