PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P1412 [ ps:P1412 wd:Q188 ] ;
    p:P463 [ ps:P463 wd:Q44687 ] ;
    p:P27 [ ps:P27 ?y1 ] ;
    p:P21 [ ps:P21 ?y2 ] ;
    p:P607 [ ps:P607 ?y3 ] ;
    p:P937 [ ps:P937 ?y4 ]
}
