PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P19 [ ps:P19 wd:Q2180 ] ;
    p:P20 [ ps:P20 wd:Q1475 ] ;
    p:P69 [ ps:P69 ?y1 ] ;
    p:P106 [ ps:P106 ?y2 ] ;
    p:P27 [ ps:P27 ?y3 ] ;
    p:P735 [ ps:P735 ?y4 ]
}
