PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P106 [ ps:P106 wd:Q82955 ] ;
    p:P735 [ ps:P735 wd:Q2829505 ] ;
    p:P734 [ ps:P734 ?y1 ] ;
    p:P21 [ ps:P21 ?y2 ] ;
    p:P39 [ ps:P39 ?y3 ] ;
    p:P27 [ ps:P27 ?y4 ]
}
