PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P106 [ ps:P106 wd:Q639669 ] ;
    p:P19 [ ps:P19 wd:Q49255 ] ;
    p:P27 [ ps:P27 ?y1 ] ;
    p:P1303 [ ps:P1303 ?y2 ] ;
    p:P735 [ ps:P735 ?y3 ] ;
    p:P21 [ ps:P21 ?y4 ]
}
