PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P641 [ ps:P641 wd:Q2736 ] ;
    p:P17 [ ps:P17 wd:Q38 ] ;
    p:P2348 [ ps:P2348 ?y1 ] ;
    p:P5138 [ ps:P5138 ?y2 ] ;
    p:P155 [ ps:P155 ?y3 ] ;
    p:P156 [ ps:P156 ?y4 ]
}
