PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P735 [ ps:P735 wd:Q545971 ] ;
    p:P108 [ ps:P108 wd:Q49115 ] ;
    p:P734 [ ps:P734 ?y1 ] ;
    p:P21 [ ps:P21 ?y2 ] ;
    p:P241 [ ps:P241 ?y3 ] ;
    p:P27 [ ps:P27 ?y4 ]
}
