PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P156 [ ps:P156 wd:Q21204822 ] ;
    p:P6216 [ ps:P6216 wd:Q19652 ] ;
    p:P361 [ ps:P361 ?y1 ] ;
    p:P1433 [ ps:P1433 ?y2 ] ;
    p:P921 [ ps:P921 ?y3 ] ;
    p:P155 [ ps:P155 ?y4 ]
}
