PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?x ?y1 ?y2
WHERE {
  ?x
    p:P19 [ ps:P19 wd:Q847130 ] ;
    p:P641 [ ps:P641 wd:Q2736 ] ;
    p:P21 [ ps:P21 ?y1 ] ;
    p:P413 [ ps:P413 ?y2 ] ;
    p:P54 [ ps:P54 ?y3 ] ;
    p:P27 [ ps:P27 ?y4 ]
}
